keys:
  - &primary age14rfyjp537j9fy3h08dd0csdc98w50ju2vlqcejqahud9h0z5ppsq30c37j
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: secrets/.*
    key_groups:
      - age:
        - *primary
